### ISSUE TITLE
Can't load the model in Python script

### ISSUE THREAD

**Issue by mirfan899** [nelson-liu/lexical-semantic-recognition#25]
I'm trying to load the model to deploy on server, but it gives error while I try to load it as follows.
```python
import allennlp
from allennlp.predictors import Predictor

Predictor.from_path("models/model.tar.gz")
```

It gives the following error
```shell
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/irfan/environments/lexical-semantic-recognition/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 257, in from_path
    return Predictor.from_archive(load_archive(archive_path, cuda_device=cuda_device), predictor_name,
  File "/home/irfan/environments/lexical-semantic-recognition/lib/python3.6/site-packages/allennlp/models/archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "/home/irfan/environments/lexical-semantic-recognition/lib/python3.6/site-packages/allennlp/models/model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/home/irfan/environments/lexical-semantic-recognition/lib/python3.6/site-packages/allennlp/common/registrable.py", line 58, in by_name
    raise ConfigurationError("%s is not a registered name for %s" % (name, cls.__name__))
allennlp.common.checks.ConfigurationError: 'streusle_tagger is not a registered name for Model'
```

Do you have a fix for this?

**Comment by nelson-liu** [comment]
I think you'll have to add the model class ( https://github.com/nelson-liu/lexical-semantic-recognition/blob/master/streusle_tagger/models/streusle_tagger.py ) into your project, and then import `StreusleTagger`. This should run the register decorator, which would allow allennlp to load the model properly.

I can also add a `setup.py` file to enable `pip` installation, which would remove the need for copying over the file---would that be helpful?

**Comment by mirfan899** [comment]
Yes it will help.

**Comment by mirfan899** [comment]
Okay, it's working now. Here is a sample for testing.
```python
import spacy
from streusle_tagger.models import streusle_tagger
from allennlp.predictors import Predictor

nlp = spacy.load("en_core_web_sm")

doc = nlp("The children enjoyed the visit to the aquarium in Coney Island")

tokens = []
lemmas = []
upos_tags = []

for span in doc:
    tokens.append(span.text)
    lemmas.append(span.lemma_)
    upos_tags.append(span.pos_)



predictor = Predictor.from_path("models/model.tar.gz", predictor_name="streusle-tagger")

print(predictor.predict_json({"tokens": tokens, "upos_tags":upos_tags, "lemmas": lemmas}))

```

**Comment by mirfan899** [comment]
One more thing. It will be helpful as well if you update the requirements with the latest version of AllenNLP and torch.

**Comment by nelson-liu** [comment]
I'm not positive the model works on the latest allennlp and torch, btw---I only tested it on the versions in the requirements.txt

**Comment by mirfan899** [comment]
Okay, sure. I will try it.

**Comment by mirfan899** [comment]
Okay, sure. I will try it.
